/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppMatchesRouteImport } from './routes/_app.matches'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppChatMatchIdRouteImport } from './routes/_app.chat.$matchId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppChatMatchIdRoute = AppChatMatchIdRouteImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/admin': typeof AppAdminRoute
  '/chat/$matchId': typeof AppChatMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/discover': typeof AppDiscoverRoute
  '/matches': typeof AppMatchesRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/admin': typeof AppAdminRoute
  '/chat/$matchId': typeof AppChatMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/matches': typeof AppMatchesRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/chat/$matchId': typeof AppChatMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/discover'
    | '/matches'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/admin'
    | '/chat/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/discover'
    | '/matches'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/admin'
    | '/chat/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/_app/discover'
    | '/_app/matches'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/admin'
    | '/_app/chat/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$matchId': {
      id: '/_app/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AppChatMatchIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppChatMatchIdRoute: typeof AppChatMatchIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminRoute: AppAdminRoute,
  AppChatMatchIdRoute: AppChatMatchIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
